# NumPy Intro

In [11]:
import numpy as np
pi = 22/7
print(pi)
print(np.pi)
print(np.cos(np.pi))
print(np.sqrt(64))
print(np.log(100))
print(np.exp(10))
print(np.log(np.exp(5.2)))

3.142857142857143
3.141592653589793
-1.0
8.0
4.605170185988092
22026.465794806718
5.2


In [9]:
vector = np.array([1,2,3])
print(f'Vector: {vector}')
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(f'\nMatrix:\n{matrix}')
print(f'\nmatrix.T: {matrix.T}')

Vector: [1 2 3]

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

matrix.T: [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [17]:
vector2 = np.arange(0,15)
print(f'Vector2: {vector2}')
vector3 = np.arange(3,22,6)
print(f'Vector3: {vector3}')

Vector2: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Vector3: [ 3  9 15 21]


In [22]:
print(np.exp(5.2))
print(pow(2.718281,5.2))

181.27224187515122
181.27195459148558


In [26]:
matrix1 = np.array([[1,2,3], [4,5,6], [7,8,9,0]])
print(f'Matrix1: {matrix1}')

Matrix1: [list([1, 2, 3]) list([4, 5, 6]) list([7, 8, 9, 0])]


C:\ProgramData\Miniconda3\envs\gl-tensorflow-gpu\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [48]:
linear_vector = np.linspace(0,5,10)
linear_tested_vector = [0*(5/9), 1*(5/9), 2*(5/9), 3*(5/9), 4*(5/9), 5*(5/9), 6*(5/9), 7*(5/9), 8*(5/9), 9*(5/9)]
print(f'\nlinear_vector:\n{linear_vector}')
print(f'\nlinear_tested_vector:\n{linear_tested_vector}')
linear_vector_reshaped = linear_vector.reshape(5,2)
print(f'\nlinear_vector_reshaped:\n{linear_vector_reshaped}')

linear_tested_vector_reshaped = np.array(linear_tested_vector).reshape(2,5)
print(f'\nlinear_tested_vector_reshaped:\n{linear_tested_vector_reshaped}')


linear_vector:
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

linear_tested_vector:
[0.0, 0.5555555555555556, 1.1111111111111112, 1.6666666666666667, 2.2222222222222223, 2.7777777777777777, 3.3333333333333335, 3.8888888888888893, 4.444444444444445, 5.0]

linear_vector_reshaped:
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]

linear_tested_vector_reshaped:
[[0.         0.55555556 1.11111111 1.66666667 2.22222222]
 [2.77777778 3.33333333 3.88888889 4.44444444 5.        ]]


In [43]:
matrix2 = np.zeros([5,3])
print(f'\nmatrix2:\n{matrix2}')
matrix3 = np.ones([3,5])
print(f'\nmatrix3:\n{matrix3}')
matrix4 = np.eye(5)
print(f'\nmatrix4:\n{matrix4}')


matrix2:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

matrix3:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

matrix4:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Arithmatic

In [47]:
first_vector = np.arange(1,6)
second_vector = np.arange(3,8)
vector_sum = first_vector + second_vector
vector_product = first_vector * second_vector
vector_diff = first_vector - second_vector
vector_div = first_vector + second_vector

one_over_first_vector = 1/first_vector
second_vector_sqrt = np.sqrt(second_vector)

print(f'\nfirst_vector:\n{first_vector}')
print(f'\nsecond_vector:\n{second_vector}')
print(f'\nvector_sum:\n{vector_sum}')
print(f'\nvector_product:\n{vector_product}')
print(f'\nvector_diff:\n{vector_diff}')
print(f'\nvector_div:\n{vector_div}')
print(f'\none_over_first_vector:\n{one_over_first_vector}')
print(f'\nsecond_vector_sqrt:\n{second_vector_sqrt}')


first_vector:
[1 2 3 4 5]

second_vector:
[3 4 5 6 7]

vector_sum:
[ 4  6  8 10 12]

vector_product:
[ 3  8 15 24 35]

vector_diff:
[-2 -2 -2 -2 -2]

vector_div:
[ 4  6  8 10 12]

one_over_first_vector:
[1.         0.5        0.33333333 0.25       0.2       ]

second_vector_sqrt:
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [57]:
# this will throw error
# five_by_two_times_two_by_five = linear_vector_reshaped * linear_tested_vector_reshaped
five_by_two_times_two_by_five = np.matmul(linear_vector_reshaped, linear_tested_vector_reshaped)
print(f'\nfive_by_two_times_two_by_five:\n{five_by_two_times_two_by_five}')
# results in a matrix of size 5X5

# can also multiply vectors
one_by_one_times_one_by_one = np.matmul(first_vector, second_vector)
# -> Multiply each element in the first vector with the element at same index in second vector and then sum all elements
print(f'\none_by_one_times_one_by_one:\n{one_by_one_times_one_by_one}')

# can multiply matrix with vector
print(f'\nVector:\n{vector}')
print(f'\nMatrix:\n{matrix}')
matrix_times_vector = np.matmul(matrix, vector)
print(f'\nmatrix_times_vector:\n{matrix_times_vector}')


five_by_two_times_two_by_five:
[[ 1.54320988  1.85185185  2.16049383  2.4691358   2.77777778]
 [ 4.62962963  6.17283951  7.71604938  9.25925926 10.80246914]
 [ 7.71604938 10.49382716 13.27160494 16.04938272 18.82716049]
 [10.80246914 14.81481481 18.82716049 22.83950617 26.85185185]
 [13.88888889 19.13580247 24.38271605 29.62962963 34.87654321]]

one_by_one_times_one_by_one:
85

Vector:
[1 2 3]

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

matrix_times_vector:
[14 32 50]


In [61]:
# solve matrix -> find solution
actual_matrix = np.array([[1,2,1],[4,5,9], [1,8,9]])
actual_vector = np.array([1,2,3])
actual_product = np.matmul(actual_matrix, actual_vector)

deduced_vector = np.linalg.solve(actual_matrix, actual_product)
print(f'\nVector:\n{actual_vector}')
print(f'\ndeduced_vector:\n{deduced_vector}')


Vector:
[1 2 3]

deduced_vector:
[1. 2. 3.]


In [63]:
# get inverse of a matrix
print(f'\nactual_matrix:\n{actual_matrix}')
print(f'\nactual_matrix inverse:\n{np.linalg.inv(actual_matrix)}')


actual_matrix:
[[1 2 1]
 [4 5 9]
 [1 8 9]]

actual_matrix inverse:
[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [65]:
# remove duplicates
vector_colours = np.array(['blue', 'orange', 'green', 'red', 'blue', 'purple', 'purple', 'red', 'orange'])
print(f'\nvector_colours:\n{vector_colours}')
print(f'\nvector_colours unique:\n{np.unique(vector_colours)}')


vector_colours:
['blue' 'orange' 'green' 'red' 'blue' 'purple' 'purple' 'red' 'orange']

vector_colours unique:
['blue' 'green' 'orange' 'purple' 'red']


In [69]:
uniform_random_matrix = np.random.rand(5,5)
standard_random_matrix = np.random.randn(15,5)
print(f'\nuniform_random_matrix:\n{uniform_random_matrix}')
print(f'\nstandard_random_matrix:\n{standard_random_matrix}')


uniform_random_matrix:
[[0.51214302 0.45964874 0.0703816  0.93068196 0.36844527]
 [0.39766034 0.1473326  0.0045609  0.88145419 0.96436768]
 [0.89206427 0.46118778 0.47851579 0.79615952 0.57761426]
 [0.59235892 0.65692585 0.84988056 0.20540321 0.95014532]
 [0.54954705 0.55849437 0.96268244 0.43943926 0.81189726]]

standard_random_matrix:
[[-1.40698078  0.4130055   0.30616193  0.22813415  0.47359563]
 [ 1.5707914   0.15153089  1.16260046  0.15726402 -1.5032177 ]
 [-1.5458265  -0.76376059  0.32900084 -0.89572343  1.54120122]
 [ 0.18850965 -0.85034592  0.79248656  1.46563585 -0.11523214]
 [-0.94826819 -0.53004169  0.58436821  1.23073745 -1.0038742 ]
 [-0.81235033  0.43281663 -0.55569427  0.06829425  2.43122806]
 [-2.26425087 -0.58084274  0.85796134 -0.15719733  0.98568314]
 [ 2.02149408  0.31723115  3.60543368 -0.34393257  0.50623105]
 [ 0.18744716  0.21297089  1.59800409 -0.27450414  0.92099129]
 [ 0.10105079  0.20450117 -1.35513507 -0.25351719  0.62758817]
 [-0.85021838  0.62280763  0.0

In [71]:
print(f'uniform_random_matrix mean:{np.mean(uniform_random_matrix)}')
print(f'uniform_random_matrix std:{np.std(uniform_random_matrix)}')

print(f'\nstandard_random_matrix mean:{np.mean(standard_random_matrix)}')
print(f'standard_random_matrix std:{np.std(standard_random_matrix)}')

print(f'\nuniform_random_matrix min:{np.min(uniform_random_matrix)}')
print(f'uniform_random_matrix max:{np.max(uniform_random_matrix)}')

print(f'\nstandard_random_matrix min:{np.min(standard_random_matrix)}')
print(f'standard_random_matrix max:{np.max(standard_random_matrix)}')

uniform_random_matrix mean:0.5807596870108386
uniform_random_matrix std:0.2816271663338159

standard_random_matrix mean:0.03951601878938953
standard_random_matrix std:1.0252172559819113

uniform_random_matrix min:0.00456089657270764
uniform_random_matrix max:0.9643676796945806

standard_random_matrix min:-2.2642508739463816
standard_random_matrix max:3.6054336829035316
