# NumPy element access

In [1]:
import numpy as np
random_vector = np.random.randn(19)
random_matrix = np.random.randn(5,5)

In [2]:
print(f'random_vector: {random_vector}')
print(f'first entry: {random_vector[0]}')
print(f'third entry: {random_vector[2]}')
print(f'first 3 entries: {random_vector[0:3]}')
print(f'last 3 entries: {random_vector[-3:]}')
print(f'last entry: {random_vector[-1:]}')
print(f'4th (inclusive) till 9th(exlusive): {random_vector[4:9]}')
print(f'4th last (inclusive) till 2nd(exlusive) last: {random_vector[-5:-1]}')

random_vector: [-0.57192962 -0.15556731  0.38883082 -1.61153191 -0.94313948 -0.36888787
  0.08739737  0.09953974 -0.2567703   0.45285015 -0.72999513 -0.45628897
 -0.05188778  0.18342652 -0.29582492 -1.10817063 -1.15255925  2.66708779
 -1.39842022]
first entry: -0.5719296182685424
third entry: 0.3888308179337427
first 3 entries: [-0.57192962 -0.15556731  0.38883082]
last 3 entries: [-1.15255925  2.66708779 -1.39842022]
last entry: [-1.39842022]
4th (inclusive) till 9th(exlusive): [-0.94313948 -0.36888787  0.08739737  0.09953974 -0.2567703 ]
4th last (inclusive) till 2nd(exlusive) last: [-0.29582492 -1.10817063 -1.15255925  2.66708779]


In [3]:
print(f'Range[Lower: 0, Upper: 15, Step:3]: {np.arange(0,15,3)}')
print(f'\nrandom_vector[np.arange(0,15,3)]: {random_vector[np.arange(0,15,3)]}')

Range[Lower: 0, Upper: 15, Step:3]: [ 0  3  6  9 12]

random_vector[np.arange(0,15,3)]: [-0.57192962 -1.61153191  0.08739737  0.45285015 -0.05188778]


In [4]:
print(f'random_matrix: \n{random_matrix}')

random_matrix: 
[[-0.21005387 -0.57794705 -1.2324251   0.38982763  0.12706357]
 [ 0.75631088  1.93962927  0.40111324  0.38305807  0.6125571 ]
 [-1.20225694  1.74791151  1.89729881  0.24534063 -0.08369318]
 [-0.74232394 -0.21115565  0.88647515 -0.41718163 -0.56185215]
 [-0.27460038  0.1897318  -0.88678404 -1.57025556 -0.31879444]]


In [5]:
print(random_matrix[0][1]) # zeroeth row -> second column
print(random_matrix[2][3]) # third row -> fourth column
print(random_matrix[0:2, 1:3])

-0.5779470539396501
0.24534062988934865
[[-0.57794705 -1.2324251 ]
 [ 1.93962927  0.40111324]]


In [6]:
# mutations
print(f'random_vector:\n{random_vector}')
random_vector[3:5] = [4]
print(f'\nrandom_vector:\n{random_vector}')
random_vector[3:5] = [4,5]
print(f'\nrandom_vector:\n{random_vector}')

random_vector:
[-0.57192962 -0.15556731  0.38883082 -1.61153191 -0.94313948 -0.36888787
  0.08739737  0.09953974 -0.2567703   0.45285015 -0.72999513 -0.45628897
 -0.05188778  0.18342652 -0.29582492 -1.10817063 -1.15255925  2.66708779
 -1.39842022]

random_vector:
[-0.57192962 -0.15556731  0.38883082  4.          4.         -0.36888787
  0.08739737  0.09953974 -0.2567703   0.45285015 -0.72999513 -0.45628897
 -0.05188778  0.18342652 -0.29582492 -1.10817063 -1.15255925  2.66708779
 -1.39842022]

random_vector:
[-0.57192962 -0.15556731  0.38883082  4.          5.         -0.36888787
  0.08739737  0.09953974 -0.2567703   0.45285015 -0.72999513 -0.45628897
 -0.05188778  0.18342652 -0.29582492 -1.10817063 -1.15255925  2.66708779
 -1.39842022]


In [7]:
print(f'random_matrix: \n{random_matrix}')
random_matrix[1:3, 3:5] = 0
print(f'random_matrix: \n{random_matrix}')

random_matrix: 
[[-0.21005387 -0.57794705 -1.2324251   0.38982763  0.12706357]
 [ 0.75631088  1.93962927  0.40111324  0.38305807  0.6125571 ]
 [-1.20225694  1.74791151  1.89729881  0.24534063 -0.08369318]
 [-0.74232394 -0.21115565  0.88647515 -0.41718163 -0.56185215]
 [-0.27460038  0.1897318  -0.88678404 -1.57025556 -0.31879444]]
random_matrix: 
[[-0.21005387 -0.57794705 -1.2324251   0.38982763  0.12706357]
 [ 0.75631088  1.93962927  0.40111324  0.          0.        ]
 [-1.20225694  1.74791151  1.89729881  0.          0.        ]
 [-0.74232394 -0.21115565  0.88647515 -0.41718163 -0.56185215]
 [-0.27460038  0.1897318  -0.88678404 -1.57025556 -0.31879444]]


In [8]:
sub_matrix = random_matrix[0:2, 0:3]
print(f'sub_matrix: \n{sub_matrix}')
sub_matrix[:] = 3
print(f'sub_matrix: \n{sub_matrix}')
print(f'random_matrix: \n{random_matrix}')

sub_matrix: 
[[-0.21005387 -0.57794705 -1.2324251 ]
 [ 0.75631088  1.93962927  0.40111324]]
sub_matrix: 
[[3. 3. 3.]
 [3. 3. 3.]]
random_matrix: 
[[ 3.          3.          3.          0.38982763  0.12706357]
 [ 3.          3.          3.          0.          0.        ]
 [-1.20225694  1.74791151  1.89729881  0.          0.        ]
 [-0.74232394 -0.21115565  0.88647515 -0.41718163 -0.56185215]
 [-0.27460038  0.1897318  -0.88678404 -1.57025556 -0.31879444]]


In [9]:
sub_matrix_copied = random_matrix[0:2, 0:3].copy()
print(f'sub_matrix_copied: \n{sub_matrix_copied}')
sub_matrix_copied[:] = 99
print(f'sub_matrix_copied: \n{sub_matrix_copied}')
print(f'random_matrix: \n{random_matrix}')

sub_matrix_copied: 
[[3. 3. 3.]
 [3. 3. 3.]]
sub_matrix_copied: 
[[99. 99. 99.]
 [99. 99. 99.]]
random_matrix: 
[[ 3.          3.          3.          0.38982763  0.12706357]
 [ 3.          3.          3.          0.          0.        ]
 [-1.20225694  1.74791151  1.89729881  0.          0.        ]
 [-0.74232394 -0.21115565  0.88647515 -0.41718163 -0.56185215]
 [-0.27460038  0.1897318  -0.88678404 -1.57025556 -0.31879444]]
