In [1]:
import tensorflow as tf
print(tf.__version__)

2.0.0


# TensorFlow Fundamentals
As per the TensorFlow website, TensorFlow is "an end-to-end open source platform for machine learning. It has a comprehensive, flexible ecosystem of tools, libraries and community resources that lets researchers push the state-of-the-art in ML and developers easily build and deploy ML powered applications."

Learning to work with tensorflow comes handy in developing ML and DL models and in this notebooks we will quickly have a look at the fundamentals/basics of tensorflow. Note that a very detailed understanding of TensorFlow are not required for this course and we will cover some very basic concepts here. You can go ahead and explore this site if you are further interested.

*Note that the notebook is for practice and expects some amount of research from the learners.
You are advised to try the code once yourself and then refer to the complete notebook.*

In [4]:
a = 4 + 2j #complex number
b = 6 + 7j

c = a + b
d = tf.square(c)
print(f'a:{a}\nb:{b}\nc:{c}\nd:{d}')

print(f'(a-b):{a-b}')
print(f'(a*b):{a*b}')

a:(4+2j)
b:(6+7j)
c:(10+9j)
d:(19+180j)
(a-b):(-2-5j)
(a*b):(10+40j)


# Tensors
As we Know, tensors are array of numbers arranged in space. We can call a vector(1-D array) as a 1st order tensor and matrix(2-D Array) as a 2nd order tensor and so on. Below, find out how to create a constant tensor:

In [5]:
c = tf.constant([[1.4, 2.0, 2], [8, 2, 5]])
print(f'c:{c}')

c:[[1.4 2.  2. ]
 [8.  2.  5. ]]


In [6]:
c

<tf.Tensor: id=6, shape=(2, 3), dtype=float32, numpy=
array([[1.4, 2. , 2. ],
       [8. , 2. , 5. ]], dtype=float32)>

You can get its value as a Numpy array by calling .numpy():

In [7]:
import numpy as np
y = np.array([[1, 2, 2], [8, 2, 5]])
print(y)
# We can also convert a tensor into a numpy array by using .numpy()
z=c.numpy()
print(z)

[[1 2 2]
 [8 2 5]]
[[1.4 2.  2. ]
 [8.  2.  5. ]]


We can get the dimensions and the datatype of the a tf.tensor as demonstrated below -

In [8]:
print('c Tensor Data Type', c.dtype)
print('c Tensor Shape', c.shape)
print('z Tensor Data Type', c.dtype)
print('z Tensor Shape', c.shape)
# You can notice the similarity with numpy 
# You can also call the different default tensors as you would do for numpy

c Tensor Data Type <dtype: 'float32'>
c Tensor Shape (2, 3)
z Tensor Data Type <dtype: 'float32'>
z Tensor Shape (2, 3)


Find a detailed reference to creating different tensors:

- [Converting python/numpy objects to tensors](https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor)
- [Generating random values from a normal distribution](https://www.tensorflow.org/api_docs/python/tf/random/normal)
- [Converting tensor values to strings](https://www.tensorflow.org/api_docs/python/tf/strings/as_string)
- [Createing a tensor of ones](https://www.tensorflow.org/api_docs/python/tf/ones)
- [Creating a tensor of zeroes](https://www.tensorflow.org/api_docs/python/tf/zeros)
- [TensorFlow for maths](https://www.tensorflow.org/api_docs/python/tf/math)

## [Variables](https://www.tensorflow.org/guide/variable) with tf.Variable()
A tensorflow Variable is a tensor that is used to store value that can later be updated. You need to initialize a variable with some value at the time of creation.

In [10]:
random_variable = tf.ones(shape=(3,3))
#random variable
tf_variable = tf.Variable(random_variable)
print(tf_variable)

#you can also update the values of your variable.
tf_variable.assign(tf.zeros(shape = (3,3)))
print(tf_variable)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>


You can find more on updating a variable [here](https://www.tensorflow.org/api_docs/python/tf/Variable#assign_add).

Now we learn about the [GradientTape](https://www.tensorflow.org/api_docs/python/tf/GradientTape) which is used to record operations for automatic differentiation.

In [11]:
# computing derivative for the function 3x^2 at x = 3

x = tf.constant(3.0) #gradient at
with tf.GradientTape() as g:
  g.watch(x) #record the operations
  y = 3*x * x
dy_dx = g.gradient(y, x) 
print(dy_dx)


# you can also use nested GradientTape() for the second derivative
#computing second derivative for the function 4x^2 at x = 4.0

x = tf.constant(4.0)
with tf.GradientTape() as gt:
  gt.watch(x)
  with tf.GradientTape() as g:
    g.watch(x)  
    y = 4*x*x
  dy_dx = g.gradient(y, x)
d2y_dx2 = gt.gradient(dy_dx,x)
print(d2y_dx2)

tf.Tensor(18.0, shape=(), dtype=float32)
tf.Tensor(8.0, shape=(), dtype=float32)


In [12]:
dy_dx

<tf.Tensor: id=55, shape=(), dtype=float32, numpy=32.0>

In [13]:
dy_dx_np = dy_dx.numpy()
dy_dx_np

32.0

In [14]:
d2y_dx2_np=d2y_dx2.numpy()
d2y_dx2_np

8.0

# Practice Questions
1. Create a constant tensor array 'x' like [2,3,4] and find element wise e^x. Refer to the website [here](https://www.tensorflow.org/api_docs/python/tf/math/exp).

In [16]:
x = tf.constant([2.0,3.0,4.0])
e_x=tf.math.exp(x)
e_x

<tf.Tensor: id=67, shape=(3,), dtype=float32, numpy=array([ 7.389056, 20.085537, 54.59815 ], dtype=float32)>

2. Declare a variable with a 3*2 shaped floating elements array with elements picked from a random normal distributions.

In [25]:
tf.random.set_seed(5);
random_tensor=tf.Variable(tf.random.normal(shape=(3,2)))
random_tensor

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[-0.18030666, -0.95028627],
       [-0.03964049, -0.7425406 ],
       [ 1.3231523 , -0.61854804]], dtype=float32)>

3. Subtract 1 from every element of the above matrix.

In [26]:
random_tensor_m_one=tf.subtract(random_tensor, 1)
random_tensor_m_one

<tf.Tensor: id=143, shape=(3, 2), dtype=float32, numpy=
array([[-1.1803067, -1.9502863],
       [-1.0396405, -1.7425406],
       [ 0.3231523, -1.618548 ]], dtype=float32)>

In [27]:
#your code here
random_tensor.assign_sub(tf.ones(shape = (3,2)))

<tf.Variable 'UnreadVariable' shape=(3, 2) dtype=float32, numpy=
array([[-1.1803067, -1.9502863],
       [-1.0396405, -1.7425406],
       [ 0.3231523, -1.618548 ]], dtype=float32)>

4. Calculate the third derivative of the function 4x^3 + x^2 + 1 at x = 1

In [20]:
x = tf.constant(1.0) #gradient at
with tf.GradientTape() as g:
  g.watch(x) #record the operations
  y = (4*x * x * x) + (x * x) + 1
dy_dx = g.gradient(y, x) 
print(dy_dx)

tf.Tensor(14.0, shape=(), dtype=float32)


In [21]:
dy_dx.numpy()

14.0

5. Calculate dot product of matrices [[1,2,3],[4,5,6],[7,8,9]] and [[1],[2],[3]] using tensorflow functions. Also, find the element wise multiplication of the two.

In [22]:
first = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
second = tf.constant([[1],[2],[3]])
tf.tensordot(first, second, 1)

<tf.Tensor: id=113, shape=(3, 1), dtype=int32, numpy=
array([[14],
       [32],
       [50]], dtype=int32)>

In [28]:
tf.matmul(first, second)

<tf.Tensor: id=148, shape=(3, 1), dtype=int32, numpy=
array([[14],
       [32],
       [50]], dtype=int32)>

In [23]:
tf.math.multiply(first,second)

<tf.Tensor: id=114, shape=(3, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]], dtype=int32)>