# CountVectorizer

In [1]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\PradeepSingh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [2]:
text = ['This is the first stage of qualification'
, 'This is the second stage of qualification '
, 'And the third one'
, 'Is it the first stage again']

In [27]:
vectorizer_vanilla = CountVectorizer()
X_count_vectorizer_vanilla = vectorizer_vanilla.fit_transform(text)
print(dict(sorted(vectorizer_vanilla.vocabulary_.items(), key=lambda item: item[1])))
print('\n')
print(vectorizer_vanilla.get_feature_names())
print(X_count_vectorizer_vanilla.toarray())
print(X_count_vectorizer_vanilla.toarray().shape)

{'again': 0, 'and': 1, 'first': 2, 'is': 3, 'it': 4, 'of': 5, 'one': 6, 'qualification': 7, 'second': 8, 'stage': 9, 'the': 10, 'third': 11, 'this': 12}


['again', 'and', 'first', 'is', 'it', 'of', 'one', 'qualification', 'second', 'stage', 'the', 'third', 'this']
[[0 0 1 1 0 1 0 1 0 1 1 0 1]
 [0 0 0 1 0 1 0 1 1 1 1 0 1]
 [0 1 0 0 0 0 1 0 0 0 1 1 0]
 [1 0 1 1 1 0 0 0 0 1 1 0 0]]
(4, 13)


In [4]:
vectorizer_word_bi_gram = CountVectorizer(analyzer='word', ngram_range=(2, 2))
X_count_vectorizer_word_bi_gram = vectorizer_word_bi_gram.fit_transform(text)
print(vectorizer_word_bi_gram.get_feature_names())
print(X_count_vectorizer_word_bi_gram.toarray())
print(X_count_vectorizer_word_bi_gram.toarray().shape)

['and the', 'first stage', 'is it', 'is the', 'it the', 'of qualification', 'second stage', 'stage again', 'stage of', 'the first', 'the second', 'the third', 'third one', 'this is']
[[0 1 0 1 0 1 0 0 1 1 0 0 0 1]
 [0 0 0 1 0 1 1 0 1 0 1 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 1 1 0]
 [0 1 1 0 1 0 0 1 0 1 0 0 0 0]]
(4, 14)


In [5]:
vectorizer_word_tri_gram = CountVectorizer(analyzer='word', ngram_range=(2, 3))
X_count_vectorizer_word_tri_gram = vectorizer_word_tri_gram.fit_transform(text)
print(vectorizer_word_tri_gram.get_feature_names())
print(X_count_vectorizer_word_tri_gram.toarray())
print(X_count_vectorizer_word_tri_gram.toarray().shape)

['and the', 'and the third', 'first stage', 'first stage again', 'first stage of', 'is it', 'is it the', 'is the', 'is the first', 'is the second', 'it the', 'it the first', 'of qualification', 'second stage', 'second stage of', 'stage again', 'stage of', 'stage of qualification', 'the first', 'the first stage', 'the second', 'the second stage', 'the third', 'the third one', 'third one', 'this is', 'this is the']
[[0 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 1 1 1 1 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 1 0 1 0 0 1 1 1 0 1 1 0 0 1 1 0 0 0 1 1]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0]
 [0 0 1 1 0 1 1 0 0 0 1 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0]]
(4, 27)


# TfidfVectorizer

In [29]:
vectorizer_tf_idf_vanilla = TfidfVectorizer()
X_tf_idf_vanilla = vectorizer_tf_idf_vanilla.fit_transform(text)
print(vectorizer_tf_idf_vanilla.vocabulary_)
print('\n')
idf = vectorizer_tf_idf_vanilla.idf_
idf_values = dict(zip(vectorizer_tf_idf_vanilla.get_feature_names(), idf))
print(idf_values)
print('\n')
print(dict(sorted(idf_values.items(), key=lambda item: item[1])))
print('\n')
print(vectorizer_tf_idf_vanilla.get_feature_names())
print(X_tf_idf_vanilla.toarray())
print(X_tf_idf_vanilla.toarray().shape)

{'this': 12, 'is': 3, 'the': 10, 'first': 2, 'stage': 9, 'of': 5, 'qualification': 7, 'second': 8, 'and': 1, 'third': 11, 'one': 6, 'it': 4, 'again': 0}


{'again': 1.916290731874155, 'and': 1.916290731874155, 'first': 1.5108256237659907, 'is': 1.2231435513142097, 'it': 1.916290731874155, 'of': 1.5108256237659907, 'one': 1.916290731874155, 'qualification': 1.5108256237659907, 'second': 1.916290731874155, 'stage': 1.2231435513142097, 'the': 1.0, 'third': 1.916290731874155, 'this': 1.5108256237659907}


{'the': 1.0, 'is': 1.2231435513142097, 'stage': 1.2231435513142097, 'first': 1.5108256237659907, 'of': 1.5108256237659907, 'qualification': 1.5108256237659907, 'this': 1.5108256237659907, 'again': 1.916290731874155, 'and': 1.916290731874155, 'it': 1.916290731874155, 'one': 1.916290731874155, 'second': 1.916290731874155, 'third': 1.916290731874155}


['again', 'and', 'first', 'is', 'it', 'of', 'one', 'qualification', 'second', 'stage', 'the', 'third', 'this']
[[0.         0.         0.4170

In [10]:
vectorizer_tf_idf_bi_gram = TfidfVectorizer(analyzer='word', ngram_range=(2,2))
X_tf_idf_bi_gram = vectorizer_tf_idf_bi_gram.fit_transform(text)
print(vectorizer_tf_idf_bi_gram.get_feature_names())
print(X_tf_idf_bi_gram.toarray())
print(X_tf_idf_bi_gram.toarray().shape)

['and the', 'first stage', 'is it', 'is the', 'it the', 'of qualification', 'second stage', 'stage again', 'stage of', 'the first', 'the second', 'the third', 'third one', 'this is']
[[0.         0.40824829 0.         0.40824829 0.         0.40824829
  0.         0.         0.40824829 0.40824829 0.         0.
  0.         0.40824829]
 [0.         0.         0.         0.37222485 0.         0.37222485
  0.47212003 0.         0.37222485 0.         0.47212003 0.
  0.         0.37222485]
 [0.57735027 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.57735027
  0.57735027 0.        ]
 [0.         0.38274272 0.48546061 0.         0.48546061 0.
  0.         0.48546061 0.         0.38274272 0.         0.
  0.         0.        ]]
(4, 14)


In [11]:
vectorizer_tf_idf_tri_gram = TfidfVectorizer(analyzer='word', ngram_range=(2,3))
X_tf_idf_tri_gram = vectorizer_tf_idf_tri_gram.fit_transform(text)
print(vectorizer_tf_idf_tri_gram.get_feature_names())
print(X_tf_idf_tri_gram.toarray())
print(X_tf_idf_tri_gram.toarray().shape)

['and the', 'and the third', 'first stage', 'first stage again', 'first stage of', 'is it', 'is it the', 'is the', 'is the first', 'is the second', 'it the', 'it the first', 'of qualification', 'second stage', 'second stage of', 'stage again', 'stage of', 'stage of qualification', 'the first', 'the first stage', 'the second', 'the second stage', 'the third', 'the third one', 'third one', 'this is', 'this is the']
[[0.         0.         0.28609357 0.         0.36287342 0.
  0.         0.28609357 0.36287342 0.         0.         0.
  0.28609357 0.         0.         0.         0.28609357 0.28609357
  0.28609357 0.28609357 0.         0.         0.         0.
  0.         0.28609357 0.28609357]
 [0.         0.         0.         0.         0.         0.
  0.         0.26684365 0.         0.33845733 0.         0.
  0.26684365 0.33845733 0.33845733 0.         0.26684365 0.26684365
  0.         0.         0.33845733 0.33845733 0.         0.
  0.         0.26684365 0.26684365]
 [0.4472136  0.

# Passing Stop Words

In [14]:
stop_words_english = set(stopwords.words("english"))
vectorizer_word_tri_gram = CountVectorizer(analyzer='word', ngram_range=(2, 3), stop_words=stop_words_english)
X_count_vectorizer_word_tri_gram = vectorizer_word_tri_gram.fit_transform(text)
print(vectorizer_word_tri_gram.get_feature_names())
print(X_count_vectorizer_word_tri_gram.toarray())
print(X_count_vectorizer_word_tri_gram.toarray().shape)

['first stage', 'first stage qualification', 'second stage', 'second stage qualification', 'stage qualification', 'third one']
[[1 1 0 0 1 0]
 [0 0 1 1 1 0]
 [0 0 0 0 0 1]
 [1 0 0 0 0 0]]
(4, 6)


In [15]:
vectorizer_tf_idf_tri_gram = TfidfVectorizer(analyzer='word', ngram_range=(2,3), stop_words=stop_words_english)
X_tf_idf_tri_gram = vectorizer_tf_idf_tri_gram.fit_transform(text)
print(vectorizer_tf_idf_tri_gram.get_feature_names())
print(X_tf_idf_tri_gram.toarray())
print(X_tf_idf_tri_gram.toarray().shape)

['first stage', 'first stage qualification', 'second stage', 'second stage qualification', 'stage qualification', 'third one']
[[0.52640543 0.66767854 0.         0.         0.52640543 0.        ]
 [0.         0.         0.61761437 0.61761437 0.48693426 0.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [1.         0.         0.         0.         0.         0.        ]]
(4, 6)


In [16]:
print(f'vectorizer_word_tri_gram: {vectorizer_word_tri_gram.vocabulary_}')
print(f'vectorizer_tf_idf_tri_gram: {vectorizer_tf_idf_tri_gram.vocabulary_}')

vectorizer_word_tri_gram: {'first stage': 0, 'stage qualification': 4, 'first stage qualification': 1, 'second stage': 2, 'second stage qualification': 3, 'third one': 5}
vectorizer_tf_idf_tri_gram: {'first stage': 0, 'stage qualification': 4, 'first stage qualification': 1, 'second stage': 2, 'second stage qualification': 3, 'third one': 5}


In [20]:
vectorizer_vanilla = CountVectorizer(stop_words= ['first','second','third'])
X_count_vectorizer_vanilla = vectorizer_vanilla.fit_transform(text)
print(vectorizer_vanilla.get_feature_names())
print(X_count_vectorizer_vanilla.toarray())
print(X_count_vectorizer_vanilla.toarray().shape)

['again', 'and', 'is', 'it', 'of', 'one', 'qualification', 'stage', 'the', 'this']
[[0 0 1 0 1 0 1 1 1 1]
 [0 0 1 0 1 0 1 1 1 1]
 [0 1 0 0 0 1 0 0 1 0]
 [1 0 1 1 0 0 0 1 1 0]]
(4, 10)


In [21]:
vectorizer_vanilla = CountVectorizer(max_features=5)
X_count_vectorizer_vanilla = vectorizer_vanilla.fit_transform(text)
print(vectorizer_vanilla.get_feature_names())
print(X_count_vectorizer_vanilla.toarray())
print(X_count_vectorizer_vanilla.toarray().shape)

['first', 'is', 'of', 'stage', 'the']
[[1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 0 0 1]
 [1 1 0 1 1]]
(4, 5)


In [30]:
vectorizer_tf_idf_vanilla = TfidfVectorizer(max_features=3)
X_tf_idf_vanilla = vectorizer_tf_idf_vanilla.fit_transform(text)
print(vectorizer_tf_idf_vanilla.get_feature_names())

['is', 'stage', 'the']
